openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: http://localhost:3000/api/v1
  - description: Health Api
    url: http://localhost:3000
info:
  description: Inverntory management System
  version: "1.0.0"
  title: Complete management system for Inventory Management
  contact:
    email: anubhav.singh@1mg.com
tags:
  - name: Health Check
    description: To check system is up or not
paths:
  /health:
    get:
      tags:
        - Health Check
      summary: Just check application is running
      operationId: checkHealth
      description: |
        Just check application is running
      responses:
        200:
          description: system is up
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                  - is_success
                  - status_code
                properties:
                  data:
                    $ref: '#/components/schemas/Health'
                  is_success:
                    type: boolean
                    example: true
                  status_code:
                    type: string
                    example: 200
components:
  schemas:
    Health:
      type: object
    Vendor:
      type: object
      required:
        - id
        - name
        - invoice_number_template
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: "Vendor Name 1"
        status:
          type: string
          enum:
            - active
            - inactive
        invoice_number_template:
          type: string
          example: ada7834n
        created:
          type: string
          example: "2016-06-15 13:39:09.36251"
        updated:
          type: string
          example: "2016-06-15 13:39:09.36251"
        metadata:
          type: object
          example: {}
    Meta:
      type: object
      required:
        - total_pages
        - total_count
      properties:
        total_pages:
          type: integer
          format: int32
          example: 10
        total_count:
          type: integer
          format: int32
          example: 130
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'this is error message'
    Errors:
      type: array
      items:
        $ref: '#/components/schemas/Error'
    ErrorObject400:
      type: object
      required:
        - errors
        - is_success
        - status_code
      properties:
        errors:
          $ref: '#/components/schemas/Errors'
        is_success:
          type: boolean
          example: false
        status_code:
          type: string
          example: 400
